// <auto-generated />
using System;
using Argus.Codex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Argus.Codex.Migrations;

[DbContext(typeof(ArgusDbContext))]
[Migration("20260614000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Argus.Codex.Entities.Host", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("AgentVersion")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("ApiKeyHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<DateTime>("FirstSeenUtc")
                .HasColumnType("TEXT");

            b.Property<DateTime>("LastSeenUtc")
                .HasColumnType("TEXT");

            b.Property<string>("MachineName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("OperatingSystem")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("ApiKeyHash");

            b.HasIndex("MachineName");

            b.ToTable("Hosts");
        });
#pragma warning restore 612, 618
    }
}
